### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by iSaluki** [Tarikul711/flutter-food-delivery-app-ui#3]
Hi,

Can you please either assign a license to this project or let me know what rights it is available under?

**Comment by galeano1990** [comment]
Estoy interesado en el proyecto

**Comment by Tarikul711** [comment]
This is an open-source project. anyone can use this project for his personal and business purpose.

**Comment by iSaluki** [comment]
So effectively the MIT license?

**Comment by Tarikul711** [comment]
ok. I will add the MIT license.
